### ISSUE TITLE
__VERSION__ naming

### ISSUE THREAD

**Issue by sourceforge807** [bashclub/check-opnsense#22]
Hi,

the version naming shows in checkmk "0.96" but it should be "2.1.0p17" (or similar) as the same of the latest supported checkmk server version.
[Reference](https://checkmk.com/integrations/checkmk_agent)

![grafik](https://user-images.githubusercontent.com/30810603/208358305-12f1ace0-1990-4173-b68f-3172c0f2878b.png)

**Comment by virus2500** [comment]
Hi, 

not the dev here, but since this agent is an alternative agent, and not an agent from checkmk itself i doubt this will be implemented. You would have to make an seperat agent for every version of checkmk available so it would match.
I would disable the check for the opnsense or show but ignore the result. I guess there is an option for this check to ignore the result.
